import type { DashboardData } from "@/types";

const isoDay = (offset: number) => {
  const date = new Date();
  date.setDate(date.getDate() + offset);
  return date.toISOString().slice(0, 10);
};

const now = () => new Date().toISOString();

export const demoDashboard: DashboardData = {
  viewer: {
    id: "avery",
    name: "Avery",
    email: "avery@example.test",
    discordId: "100000000000000001",
    systemRole: "admin",
    active: true,
    groupRoles: { "show-crew": "organizer", "site-crew": "member" },
  },
  people: [
    {
      id: "avery",
      name: "Avery",
      email: "avery@example.test",
      discordId: "100000000000000001",
      systemRole: "admin",
      active: true,
      groupRoles: { "show-crew": "organizer", "site-crew": "member" },
    },
    {
      id: "maya",
      name: "Maya",
      email: "maya@example.test",
      discordId: "100000000000000002",
      systemRole: "member",
      active: true,
      groupRoles: { "show-crew": "member", "site-crew": "organizer" },
    },
    {
      id: "jules",
      name: "Jules",
      email: "jules@example.test",
      discordId: "100000000000000003",
      systemRole: "member",
      active: true,
      groupRoles: { "show-crew": "member" },
    },
    {
      id: "sam",
      name: "Sam",
      email: "sam@example.test",
      discordId: "100000000000000004",
      systemRole: "member",
      active: true,
      groupRoles: { "site-crew": "member" },
    },
  ],
  groups: [
    {
      id: "show-crew",
      name: "Show Crew",
      slug: "show-crew",
      icon: "pumpkin",
      accent: "pumpkin",
      isPrivate: true,
      discordChannelId: "123456789012345678",
      recapEnabled: true,
      recapHourUtc: 15,
    },
    {
      id: "site-crew",
      name: "Site Crew",
      slug: "site-crew",
      icon: "ghost",
      accent: "purple",
      isPrivate: true,
      discordChannelId: null,
      recapEnabled: false,
      recapHourUtc: 15,
    },
  ],
  boards: [
    {
      id: "opening-night",
      groupId: "show-crew",
      name: "Opening Night",
      slug: "opening-night",
      note: "The shared run-up to our first night.",
    },
    {
      id: "website-refresh",
      groupId: "site-crew",
      name: "Website Refresh",
      slug: "website-refresh",
      note: "A calmer home for the stream and controls.",
    },
  ],
  columns: [
    ...["Ideas", "Up Next", "Doing", "Waiting", "Done"].map((name, index) => ({
      id: `opening-${index}`,
      boardId: "opening-night",
      name,
      rank: (index + 1) * 1024,
      color: ["purple", "pumpkin", "green", "berry", "neutral"][index],
    })),
    ...["Ideas", "Up Next", "Doing", "Waiting", "Done"].map((name, index) => ({
      id: `web-${index}`,
      boardId: "website-refresh",
      name,
      rank: (index + 1) * 1024,
      color: ["purple", "pumpkin", "green", "berry", "neutral"][index],
    })),
  ],
  tags: [
    {
      id: "run-of-show",
      groupId: "show-crew",
      name: "run of show",
      color: "purple",
    },
    {
      id: "needs-check",
      groupId: "show-crew",
      name: "needs a check",
      color: "pumpkin",
    },
    { id: "web", groupId: "site-crew", name: "web", color: "green" },
  ],
  cards: [
    {
      id: "card-1",
      key: "SHOW-12",
      boardId: "opening-night",
      columnId: "opening-2",
      title: "Map the full run-through",
      notes:
        "Capture the handoffs and the moments where we want an extra pair of eyes.",
      importance: "high",
      when: isoDay(1),
      blocked: false,
      blockedReason: null,
      rank: 1024,
      version: 3,
      personIds: ["avery", "maya"],
      tagIds: ["run-of-show"],
      checklist: [
        {
          id: "check-1",
          text: "Share the first draft",
          complete: true,
          rank: 1024,
        },
        {
          id: "check-2",
          text: "Mark handoff points",
          complete: false,
          rank: 2048,
        },
      ],
      comments: [
        {
          id: "comment-1",
          authorId: "maya",
          body: "I added the arrival window from our last chat.",
          createdAt: new Date(Date.now() - 3_600_000).toISOString(),
        },
      ],
      links: [],
      changes: [
        {
          id: "change-1",
          actorId: "maya",
          kind: "comment_added",
          summary: "A note was added to Map the full run-through.",
          createdAt: new Date(Date.now() - 3_600_000).toISOString(),
        },
      ],
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "card-2",
      key: "SHOW-14",
      boardId: "opening-night",
      columnId: "opening-1",
      title: "Confirm everyone’s arrival window",
      notes: "A quick check so nobody has to guess where to be.",
      importance: "medium",
      when: isoDay(2),
      blocked: false,
      blockedReason: null,
      rank: 1024,
      version: 1,
      personIds: ["jules"],
      tagIds: ["needs-check"],
      checklist: [],
      comments: [],
      links: [],
      changes: [],
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "card-3",
      key: "SHOW-16",
      boardId: "opening-night",
      columnId: "opening-3",
      title: "Choose a backup meeting spot",
      notes: "Waiting on one final availability check.",
      importance: "low",
      when: isoDay(4),
      blocked: true,
      blockedReason: "Need the venue confirmation",
      rank: 1024,
      version: 2,
      personIds: ["avery"],
      tagIds: [],
      checklist: [],
      comments: [],
      links: [],
      changes: [],
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "card-4",
      key: "WEB-21",
      boardId: "website-refresh",
      columnId: "web-2",
      title: "Review welcome screen copy",
      notes: "Keep the invitation warm and explain the controls in one breath.",
      importance: "medium",
      when: isoDay(3),
      blocked: false,
      blockedReason: null,
      rank: 1024,
      version: 4,
      personIds: ["maya", "sam"],
      tagIds: ["web"],
      checklist: [
        { id: "check-3", text: "Read it aloud", complete: true, rank: 1024 },
        {
          id: "check-4",
          text: "Check mobile wrapping",
          complete: false,
          rank: 2048,
        },
      ],
      comments: [],
      links: [
        {
          id: "link-1",
          kind: "github_issue",
          url: "https://github.com/octocat/Hello-World/issues/1",
          owner: "octocat",
          repo: "Hello-World",
          issueNumber: 1,
          title: "Example linked issue",
          state: "unknown",
        },
      ],
      changes: [],
      createdAt: now(),
      updatedAt: now(),
    },
  ],
  activity: [
    {
      id: "activity-1",
      actorId: "maya",
      groupId: "show-crew",
      boardId: "opening-night",
      cardId: "card-1",
      kind: "comment",
      summary: "added a note to SHOW-12",
      createdAt: new Date(Date.now() - 3_600_000).toISOString(),
    },
    {
      id: "activity-2",
      actorId: "avery",
      groupId: "show-crew",
      boardId: "opening-night",
      cardId: "card-3",
      kind: "blocked",
      summary: "moved SHOW-16 to Waiting",
      createdAt: new Date(Date.now() - 7_200_000).toISOString(),
    },
  ],
};
