import type { DashboardData } from "./types";

const today = new Date();
const isoOffset = (days: number) => {
  const next = new Date(today);
  next.setDate(today.getDate() + days);
  return next.toISOString().slice(0, 10);
};

export const demoDashboard: DashboardData = {
  demoMode: true,
  savedViews: [],
  notificationPreferences: {
    assignments: true,
    mentions: true,
    dueSoon: true,
    digest: "daily",
    quietStart: null,
    quietEnd: null,
    timezone: "America/New_York",
  },
  viewer: {
    id: "demo-avery",
    name: "Avery",
    email: "avery@example.test",
    discordId: "100000000000000001",
    systemRole: "admin",
    active: true,
    groupRoles: {
      "group-show": "organizer",
      "group-site": "member",
      "group-comms": "view_only",
    },
  },
  people: [
    {
      id: "demo-avery",
      name: "Avery",
      email: "avery@example.test",
      discordId: "100000000000000001",
      systemRole: "admin",
      active: true,
      groupRoles: {
        "group-show": "organizer",
        "group-site": "member",
        "group-comms": "view_only",
      },
    },
    {
      id: "demo-maya",
      name: "Maya",
      email: "maya@example.test",
      discordId: "100000000000000002",
      systemRole: "member",
      active: true,
      groupRoles: {
        "group-show": "member",
        "group-site": "organizer",
      },
    },
    {
      id: "demo-jules",
      name: "Jules",
      email: "jules@example.test",
      discordId: "100000000000000003",
      systemRole: "member",
      active: true,
      groupRoles: {
        "group-show": "member",
        "group-comms": "organizer",
      },
    },
    {
      id: "demo-sam",
      name: "Sam",
      email: "sam@example.test",
      discordId: "100000000000000004",
      systemRole: "member",
      active: true,
      groupRoles: {
        "group-site": "member",
        "group-comms": "member",
      },
    },
  ],
  groups: [
    {
      id: "group-show",
      name: "Show Crew",
      slug: "show-crew",
      icon: "pumpkin",
      accent: "pumpkin",
      isPrivate: true,
      discordChannelId: "123456789012345678",
      recapEnabled: true,
      recapHourUtc: 15,
    },
    {
      id: "group-site",
      name: "Site Crew",
      slug: "site-crew",
      icon: "ghost",
      accent: "purple",
      isPrivate: true,
      discordChannelId: null,
      recapEnabled: false,
      recapHourUtc: 15,
    },
    {
      id: "group-comms",
      name: "Comms Crew",
      slug: "comms-crew",
      icon: "bat",
      accent: "green",
      isPrivate: true,
      discordChannelId: null,
      recapEnabled: false,
      recapHourUtc: 15,
    },
  ],
  boards: [
    {
      id: "board-opening",
      groupId: "group-show",
      name: "Opening Night",
      slug: "opening-night",
      note: "The shared run-up to our first night.",
    },
    {
      id: "board-web",
      groupId: "group-site",
      name: "Website Refresh",
      slug: "website-refresh",
      note: "A calmer, clearer home for the experience.",
    },
    {
      id: "board-outreach",
      groupId: "group-comms",
      name: "Community Notes",
      slug: "community-notes",
      note: "Messages, acknowledgements, and helpful links.",
    },
  ],
  columns: [
    ...["Ideas", "Up Next", "Doing", "Waiting", "Done"].map((name, index) => ({
      id: `opening-${index}`,
      boardId: "board-opening",
      name,
      rank: (index + 1) * 1024,
      color: ["purple", "pumpkin", "green", "berry", "neutral"][index],
    })),
    ...["Ideas", "Up Next", "Doing", "Waiting", "Done"].map((name, index) => ({
      id: `web-${index}`,
      boardId: "board-web",
      name,
      rank: (index + 1) * 1024,
      color: ["purple", "pumpkin", "green", "berry", "neutral"][index],
    })),
    ...["Ideas", "Up Next", "Doing", "Waiting", "Done"].map((name, index) => ({
      id: `outreach-${index}`,
      boardId: "board-outreach",
      name,
      rank: (index + 1) * 1024,
      color: ["purple", "pumpkin", "green", "berry", "neutral"][index],
    })),
  ],
  tags: [
    {
      id: "tag-together",
      groupId: "group-show",
      name: "together",
      color: "purple",
    },
    {
      id: "tag-check",
      groupId: "group-show",
      name: "needs a check",
      color: "pumpkin",
    },
    { id: "tag-copy", groupId: "group-site", name: "words", color: "green" },
    {
      id: "tag-design",
      groupId: "group-site",
      name: "visual",
      color: "purple",
    },
    {
      id: "tag-community",
      groupId: "group-comms",
      name: "community",
      color: "green",
    },
  ],
  cards: [
    {
      id: "card-1",
      key: "SHOW-12",
      boardId: "board-opening",
      columnId: "opening-2",
      title: "Map the full run-through",
      notes:
        "Capture the order, the handoffs, and the moments where we want an extra pair of eyes.",
      importance: "high",
      when: isoOffset(1),
      blocked: false,
      blockedReason: null,
      rank: 1024,
      version: 3,
      personIds: ["demo-avery", "demo-maya"],
      tagIds: ["tag-together"],
      checklist: [
        {
          id: "check-1",
          text: "Share the first draft",
          complete: true,
          rank: 1024,
        },
        {
          id: "check-2",
          text: "Mark handoff points",
          complete: false,
          rank: 2048,
        },
        {
          id: "check-3",
          text: "Leave room for notes",
          complete: false,
          rank: 3072,
        },
      ],
      comments: [
        {
          id: "comment-1",
          authorId: "demo-maya",
          body: "I added the arrival window from our last chat.",
          createdAt: new Date(Date.now() - 3_600_000).toISOString(),
        },
      ],
      links: [],
      createdAt: new Date(Date.now() - 172_800_000).toISOString(),
      updatedAt: new Date(Date.now() - 3_600_000).toISOString(),
    },
    {
      id: "card-2",
      key: "SHOW-14",
      boardId: "board-opening",
      columnId: "opening-1",
      title: "Confirm everyone’s arrival window",
      notes: "A quick check so nobody has to guess where they should be.",
      importance: "medium",
      when: isoOffset(2),
      blocked: false,
      blockedReason: null,
      rank: 1024,
      version: 1,
      personIds: ["demo-jules"],
      tagIds: ["tag-check"],
      checklist: [],
      comments: [],
      links: [],
      createdAt: new Date(Date.now() - 86_400_000).toISOString(),
      updatedAt: new Date(Date.now() - 86_400_000).toISOString(),
    },
    {
      id: "card-3",
      key: "SHOW-16",
      boardId: "board-opening",
      columnId: "opening-3",
      title: "Choose a backup meeting spot",
      notes: "Waiting on one final availability check.",
      importance: "low",
      when: isoOffset(4),
      blocked: true,
      blockedReason: "Need the venue confirmation",
      rank: 1024,
      version: 2,
      personIds: ["demo-avery"],
      tagIds: [],
      checklist: [],
      comments: [],
      links: [],
      createdAt: new Date(Date.now() - 259_200_000).toISOString(),
      updatedAt: new Date(Date.now() - 7_200_000).toISOString(),
    },
    {
      id: "card-4",
      key: "WEB-21",
      boardId: "board-web",
      columnId: "web-2",
      title: "Review welcome screen copy",
      notes: "Keep the invitation warm and explain the controls in one breath.",
      importance: "medium",
      when: isoOffset(3),
      blocked: false,
      blockedReason: null,
      rank: 1024,
      version: 4,
      personIds: ["demo-maya", "demo-sam"],
      tagIds: ["tag-copy"],
      checklist: [
        { id: "check-4", text: "Read it aloud", complete: true, rank: 1024 },
        {
          id: "check-5",
          text: "Check mobile wrapping",
          complete: false,
          rank: 2048,
        },
      ],
      comments: [],
      links: [
        {
          id: "link-1",
          kind: "github_issue",
          url: "https://github.com/octocat/Hello-World/issues/1",
          owner: "octocat",
          repo: "Hello-World",
          issueNumber: 1,
          title: "Example linked issue",
          state: "unknown",
        },
      ],
      createdAt: new Date(Date.now() - 345_600_000).toISOString(),
      updatedAt: new Date(Date.now() - 14_400_000).toISOString(),
    },
    {
      id: "card-5",
      key: "WEB-24",
      boardId: "board-web",
      columnId: "web-0",
      title: "Collect visual references",
      notes:
        "A small, intentional set—only examples we actually want to discuss.",
      importance: "none",
      when: null,
      blocked: false,
      blockedReason: null,
      rank: 1024,
      version: 1,
      personIds: [],
      tagIds: ["tag-design"],
      checklist: [],
      comments: [],
      links: [],
      createdAt: new Date(Date.now() - 43_200_000).toISOString(),
      updatedAt: new Date(Date.now() - 43_200_000).toISOString(),
    },
    {
      id: "card-6",
      key: "COMMS-8",
      boardId: "board-outreach",
      columnId: "outreach-1",
      title: "Gather collaborator credits",
      notes: "Names, links, and how each person would like to be credited.",
      importance: "medium",
      when: isoOffset(5),
      blocked: false,
      blockedReason: null,
      rank: 1024,
      version: 1,
      personIds: ["demo-jules"],
      tagIds: ["tag-community"],
      checklist: [],
      comments: [],
      links: [],
      createdAt: new Date(Date.now() - 216_000_000).toISOString(),
      updatedAt: new Date(Date.now() - 21_600_000).toISOString(),
    },
  ],
  activity: [
    {
      id: "activity-1",
      actorId: "demo-maya",
      groupId: "group-show",
      boardId: "board-opening",
      cardId: "card-1",
      kind: "commented",
      summary: "left a note on Map the full run-through",
      createdAt: new Date(Date.now() - 3_600_000).toISOString(),
    },
    {
      id: "activity-2",
      actorId: "demo-avery",
      groupId: "group-show",
      boardId: "board-opening",
      cardId: "card-3",
      kind: "blocked",
      summary: "marked Choose a backup meeting spot as waiting",
      createdAt: new Date(Date.now() - 7_200_000).toISOString(),
    },
    {
      id: "activity-3",
      actorId: "demo-sam",
      groupId: "group-site",
      boardId: "board-web",
      cardId: "card-4",
      kind: "updated",
      summary: "updated the notes on Review welcome screen copy",
      createdAt: new Date(Date.now() - 14_400_000).toISOString(),
    },
  ],
};
